unchanged:
--- setuptools_scm-2.1.0.orig/setuptools_scm/file_finder_git.py	2018-05-20 21:10:53.786520000 -0400
+++ setuptools_scm-2.1.0/setuptools_scm/file_finder_git.py	2018-05-20 21:12:10.709621400 -0400
@@ -10,7 +10,7 @@
         with open(os.devnull, 'wb') as devnull:
             out = subprocess.check_output([
                 'git', 'rev-parse', '--show-toplevel',
-            ], cwd=(path or '.'), universal_newlines=True, stderr=devnull)
+            ], cwd=(path), universal_newlines=True, stderr=devnull)
         return os.path.normcase(os.path.realpath(out.strip()))
     except subprocess.CalledProcessError:
         # git returned error, we are not in a git repo
only in patch2:
unchanged:
--- setuptools_scm-2.1.0/setuptools_scm/file_finder_hg.py.orig	2018-05-20 21:17:07.794217600 -0400
+++ setuptools_scm-2.1.0/setuptools_scm/file_finder_hg.py	2018-05-20 21:17:15.727334000 -0400
@@ -9,7 +9,7 @@
         with open(os.devnull, 'wb') as devnull:
             out = subprocess.check_output([
                 'hg', 'root',
-            ], cwd=(path or '.'), universal_newlines=True, stderr=devnull)
+            ], cwd=(path), universal_newlines=True, stderr=devnull)
         return os.path.normcase(os.path.realpath(out.strip()))
     except subprocess.CalledProcessError:
         # hg returned error, we are not in a mercurial repo
